language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jmesmero/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jmesmero/docker-react npm run test
 